language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t sokoler/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sokoler/react-test npm test

after_success:
  - docker build -t sokoler/multi-client ./client
  - docker build -t sokoler/multi-nginx ./nginx
  - docker build -t sokoler/multi-server ./server
  - docker build -t sokoler/multi-worker ./worker
  #log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push the Images to Docker hub
  - docker push sokoler/multi-client
  - docker push sokoler/multi-nginx
  - docker push sokoler/multi-server
  - docker push sokoler/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi_docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-890646895555
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
